### PR TITLE
Feat: New docs internal integration

### PR DESCRIPTION
**Pull request by dashcraft**
Uses nextra to generate docs internal to the next application.

I had to manipulate the nextra docs theme to be prefixed, so there's a chunk of generator code
with a prefix applied to prevent styles from bleeding over.

I'll be getting with @yusefnapora to verify I didn't break anything from our previous docs build.

## Remaining

- [x] Adjust tablet breaks to prevent content cutoff (>768 and ~ <1048) https://github.com/nftstorage/nft.storage/pull/1044#issuecomment-1031907653

### CODE REVIEW

**Comment by redaphid** [comment]
Should we add these generated files to .gitignore?

**Comment by yusefnapora** [comment]
Looks good to me so far 👍

I'll start basing content edits off of this branch so we stay in sync.

**Comment by dashcraft** [comment]
> Looks good to me so far 👍
> 
> I'll start basing content edits off of this branch so we stay in sync.

I need to remove the docs.module.css file, its no longer needed fwiw, i also need to fix the broken images.

**Comment by JeffLowe** [comment]
If a user clicks on page links leading away from /docs ( eg the /manage page link https://nft.storage/manage/ found on the Architecture Considerations page https://c04825bd.nft-storage-1at.pages.dev/docs/concepts/architecture-considerations/) , then browser back button back to the docs, the route changes correctly but the homepage loads with broken images.
Also, direct links to those docs pages do not load (instead, load homepage with broken images).  eg opening this direct link: https://c04825bd.nft-storage-1at.pages.dev/docs/

**Comment by yusefnapora** [comment]
hey @dashcraft I noticed today that anchor links to page headings don't seem to be working - clicking the TOC entries on the left nav don't seem to scroll to the right section in the doc. Is that a nextra setting we're missing or something?

**Comment by dashcraft** [comment]
> hey @dashcraft I noticed today that anchor links to page headings don't seem to be working - clicking the TOC entries on the left nav don't seem to scroll to the right section in the doc. Is that a nextra setting we're missing or something?

You might pull latest, I disabled/removed all sub links, nextra has a bug in their headings that has been fix on an upcoming release that isn't stable yet.

The left hand navigation should work for all top level nav elements/pages, but the "section" navigation has been disabled by using h3's and not h2's.

**Comment by dashcraft** [comment]
https://github.com/shuding/nextra/issues/321

**Comment by yusefnapora** [comment]
ah right on - yeah I didn't notice your commit that removed the sub links. Sad, but hopefully we can just wait for a bit and get the fix.

**Comment by Codigo-Fuentes** [comment]
Screen Shot 2022-02-02 at 1 18 24 PM
Screen Shot 2022-02-02 at 1 20 12 PM

**suggestion(non-blocking)**: the bottom border of `.nextra-container h2` and an `<hr>` in the footer have very low contrast. I would consider changing the color or (in the case of the h2 element) removing.

**Comment by Codigo-Fuentes** [comment]
Screen Shot 2022-02-02 at 3 20 10 PM

Updating spacing of headings, links black.

**Comment by Codigo-Fuentes** [comment]
Screen Shot 2022-02-02 at 3 22 11 PM

Vertical margin on images.

**Comment by Codigo-Fuentes** [comment]
Screen Shot 2022-02-02 at 3 23 32 PM

Reduced space between title and text in callouts (1.5rem -> 1rem)

**Comment by cmunns** [comment]
Deps not displaying correctly and badges should be inline with some space between. Screen Shot 2022-02-07 at 12 21 21 PM

**Comment by cmunns** [comment]
Raw HTTP links to /#api-docs but on prod the anchor link is /#docs
Screen Shot 2022-02-07 at 12 30 34 PM

**Comment by cmunns** [comment]
We will need to either have the overflow for the menu be flush with the bottom or add a border/drop-shadow or something to indicate the menu container, without it the screenshot is not showing "lib" at the bottom of the menu and its impossible to know it's getting cut off at all.
Screen Shot 2022-02-07 at 12 38 51 PM

**Comment by cmunns** [comment]
Above 768px we get cutoff content.
Screen Shot 2022-02-07 at 12 43 31 PM

Related but different in why it happens we have more overflow coming from the ipfs string not being given an overflow container like seen higher up in the screenshot:
Screen Shot 2022-02-07 at 12 49 21 PM

**Comment by cmunns** [comment]
Another link needing mobile treatment
Screen Shot 2022-02-07 at 1 01 34 PM

**Pull request merged**
