### PR TITLE
fix: config loading

### PR DESCRIPTION
**Pull request by hugomrdias**
Should fix config loading issue reported here https://github.com/nftstorage/nft.storage/pull/1914#issuecomment-1144590892

### CODE REVIEW

**Review by vasco-santos — APPROVED** [review]
LGTM

**Review by yusefnapora — APPROVED** [review]
Very nice, thanks @hugomrdias. I like that you moved the default config values out of the code and into the template env. In hindsight its simpler to have just the one source of truth.

**Comment by yusefnapora** [comment]
@hugomrdias I'll go ahead and merge, since this was blocking production deploys.

**Comment by vasco-santos** [comment]
Awesome thanks @hugomrdias and @yusefnapora . Deploys are now working 🎉

**Pull request merged**
