### PR TITLE
feat: Q3'22 integration blog post

### PR DESCRIPTION
**Pull request by dchoi27**
Remaining tasks:

- [x] Center and make the size consistent across all the logo images in the post
- [x] Update the date in the post to when this gets merged / deployed

### CODE REVIEW

**Comment by TkKonstantin** [comment]
Link to the blogpost image from design team https://github.com/protocol/design-shop/issues/1497, CID: bafkreidwm7v7mn5t3nbn3xp7a3vve3h6v6awjunpngjo4fpvqi7xwxwnde

Announcement collab images: 
Dvision network CID: bafkreidlhlvth5gftxszrqxm4agx4fksm6xqsnsgnemeeeafglv2oadkim
Limewire CID: bafkreifybdnlelyxly3taskhxrzktbaj65cunft67423qzxztugc37sfuu
Label Foundation CID: bafybeia3n3ktas7l2matfipwi77phdo6hjmijnojwq6vmx65awuk7him7m

Also, with Mosh we discussed that the announcement images might not look ideal for the blog post. Let's also give a shot just with their logos and see what looks better:
Dvision network Logo CID: bafkreibwium32xss34d4zozmibrovh4ueif2ppuuuzd4d66xl3d2t5y47y
Limewire Logo CID: bafkreidsy5csbjytcfhy56dpcwlgy2xmjka3dbaavnljhiioukwln3nlmy
Label Foundation Logo CID: bafkreigr3yfl5hzsrpv62udg7pwbopchzgyojcrml4pawc4te63624hm3e

**Comment by dchoi27** [comment]
@JeffLowe could someone help:
- Center and make the size consistent across all the logo images in the post?
- Update the date in the post to when this gets merged / deployed?

Thanks!

**Comment by johnathonroach** [comment]
@dchoi27 @JeffLowe Here is some initial formatting for the images. I have them centered and set to 50% width.

Preview link
https://f736b604.nft-storage-1at.pages.dev/blog/post/2022-06-22-spring-integration-spotlights/

**Review by JeffLowe — APPROVED** [review]
Reviewed preview link in multiple browsers (Safari, Chrome, Brave) and on mobile.  Logos, layout looks good.  Links work and lead to right spots.

**Review by johnathonroach — APPROVED** [review]

**Pull request merged**
