### PR TITLE
fix: lots of small optimizations led to big gains

### PR DESCRIPTION
**Pull request by dashcraft**
I made some changes, the original starting point for me locally was 63% for performance.

Naturally, these changes may not entirely propagate the same results in prod, but this is a decent measurement that performance.

Need to optimize images more though.

image

### CODE REVIEW

**Comment by the-simian** [comment]
Unfortunately the cloudflare build broke but I can still provide some feedback in some places that tI think will still help this PR

**Comment by the-simian** [comment]
Honestly I'm amazed at how much the next Image component really helped performance, good work.

**Comment by hugomrdias** [comment]
can you please remove the sitemap.xml? probably should go into the git ignore to avoid this in the future.

```bash
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
--
23:07:17.811 | Possible solutions:
23:07:17.811 | - Use `next start` to run a server, which includes the Image Optimization API.
23:07:17.811 | - Use any provider which supports Image Optimization (like Vercel).
23:07:17.811 | - Configure a third-party loader in `next.config.js`.
23:07:17.811 | - Use the `loader` prop for `next/image`.
23:07:17.811 | Read more: https://nextjs.org/docs/messages/export-image-api
```

FYI this fails in the same way locally when you run `yarn build`

You can't use `next/image` like this, it does not work with static exports. You should do something like i described in https://github.com/nftstorage/nft.storage/issues/1653.

**Comment by hugomrdias** [comment]
you can use something like `image-size` inside a `getStaticProps` to get the original sizes when needed

**Review by the-simian — APPROVED** [review]
1. I see you got the cloudflare image in here: https://github.com/nftstorage/nft.storage/blob/2ad0687f67b6c093211b7ef89a04a861cde586a5/packages/website/components/cloudflareImage.js
2. and you implemented the code changes to get lodash out.  
3. I also ran a perf check:
Screen Shot 2022-03-28 at 10 37 03 AM

So I think we're good!

**Pull request merged**
