### PR TITLE
Massively overhauled the user authentication

### LINKED ISSUE #1349: Logged in state lost when user switches to /docs route
When logged in user navigates to /docs, they appear to lose logged in state (top nav changes to logged out state).  However, if they navigagte back to homepage or elsewhere, they regain logged in state. 

## User is logged in
Screen Shot 2022-02-11 at 10 14 48 AM
## User appears logged out upon navigating to /docs
Screen Shot 2022-02-11 at 10 15 03 AM

### PR DESCRIPTION
**Pull request by dashcraft**
Save to local storage and check before reissuing request to magic auth. If we want, we can manually refresh in the background, but if a user has already auth'd we shouldn't be issuing a request on every render.

I also drastically simplified the redirect logic and the nested layout logic to be much slimmer.

Fixes #1349

### CODE REVIEW

**Comment by dashcraft** [comment]
Cloudflare build 934 is outdated, a new one hasn't triggered, for anyone testing.

**Comment by Codigo-Fuentes** [comment]
**praise**: Auth refactor looks like a much better pattern.

**Comment by Codigo-Fuentes** [comment]
**issue (blocking)**: There is jank when user navigates from /docs by clicking the "about" link in header.

https://user-images.githubusercontent.com/43380153/155129272-b6bafdba-503c-45c5-9ba9-43042856d349.mp4

**Review by Codigo-Fuentes — CHANGES_REQUESTED** [review]
**issue (blocking)**: There is jank when user navigates from /docs by clicking the "about" link in header.

https://user-images.githubusercontent.com/43380153/155129272-b6bafdba-503c-45c5-9ba9-43042856d349.mp4

**Comment by Codigo-Fuentes** [comment]
**praise**: Auth refactor looks like a much better pattern!

**Review by Codigo-Fuentes — APPROVED** [review]

**Comment by dashcraft** [comment]
@hugomrdias here is the original pr with comments, I'm linking your comment below, if you can read over this and see if it fills any gaps, i can double back and check your comments shortly.

link to original comment:
https://github.com/nftstorage/nft.storage/pull/1495#issuecomment-1058139163

**Comment by hugomrdias** [comment]
it does not fill in the gaps sorry, still have the same concerns

**Pull request merged**
