### PR TITLE
chore: update copy based on dchoi's feedback

### LINKED ISSUE #893: Edit language on homepage on website to make value prop more clear
Right now, the language on the website assumes a bit too much knowledge about the benefits of using IPFS when trying to illustrate the value of NFT.Storage. Let's spell this out a bit more, and where Filecoin comes into play.

Can we make the following language changes to the homepage:
- [ ] Add an "and 10,000+ other users!" underneath logos
- [ ] ensure the last paragraph currently in About (To learn more about the importance of content addressing ...) gets deleted (it is not included in the updated copy below)
- [ ] Under `About`:
```
NFT.Storage is a long-term storage service designed for off-chain NFT data (like metadata, images, and other assets) for up to 31GiB in size. Data is [content addressed](https://nftschool.dev/concepts/content-addressing) using IPFS, meaning the URL pointing to a piece of data (“ipfs://...”) is completely unique to that data. IPFS URLs can be used in NFTs and their metadata to ensure the an NFT forever actually refers to the intended data (eliminating things like rug pulls).

NFT.Storage stores many copies of uploaded data on the public IPFS network in two primary ways: in dedicated IPFS servers managed by NFT.Storage, and decentralized on [Filecoin](https://filecoin.io/). Since IPFS is a standard used by many different storage services, it’s easy to redundantly store data uploaded to NFT.Storage on any other IPFS-compatible storage solution from [pinning services](https://docs.ipfs.io/how-to/work-with-pinning-services/), to your [local IPFS node](https://docs.ipfs.io/install/ipfs-desktop), to other decentralized networks like Arweave or Storj.
```

- [ ]  in ABOUT section, change the current single column to a 2 column layout as seen in figma
### Current ABOUT
image

### NEW ABOUT
image

- [ ] Modify `Store`:
```
Just upload your data and you'll receive an IPFS hash of the content (a "CID," or content address) that you can use to make an IPFS URL (`ipfs://<cid>`). Use this IPFS URL in your NFT data to refer to off-chain data (e.g., the metadata field in your NFT, the image field in your metadata) as a pointer to the content.

Filecoin provides long-term storage for the data ensuring that even if NFT.Storage is attacked or taken down the NFT data persists! And NFT.Storage will continue to decentralize itself out of the picture moving forward (e.g., making perpetual storage completely smart contract-based utilizing future tools like the [Filecoin Virtual Machine](https://filecoin.io/blog/posts/introducing-the-filecoin-virtual-machine/)).

Have additional preferences on where to store your data? Pin your data to any storage solution running a [pinning service API](https://ipfs.github.io/pinning-services-api-spec/).
```
- [ ] Change "nft.storage" to "NFT.Storage" throughout the homepage

### PR DESCRIPTION
**Pull request by dashcraft**
chore: update copy based on dchoi's feedback

Fixes #893

### CODE REVIEW

**Comment by dashcraft** [comment]
image

**Comment by dashcraft** [comment]
image

**Review by the-simian — APPROVED** [review]
From a code perspective, this is about as straightforward as can be - all looks fine to merge. I added @dchoi27 as a reviewer to give the copy itself a once-over. After that, I think we should merge it

**Comment by dchoi27** [comment]
Thanks! Having the About section be this long and pushing the diagram down doesn't look great. Can we try centering the About section at the top, and then having the Store and Retrieve section around the diagram look like how it was before (think the main thing is for the Store section to be higher on the page relative to the diagram vs. how it is in the preview?

I'm going to edit the About section copy a bit as well - will update the issue with the adjusted copy.

**Comment by dashcraft** [comment]
Asks:
- [ ] Add an "and 10,000+ other users!" underneath logos
- [ ] ensure the last paragraph currently in About (To learn more about the importance of content addressing ...) gets deleted (it is not included in the updated copy below)
- [ ] Under `About` copy updates
- [ ] Modify `Store` copy updates
- [ ] Change "nft.storage" to "NFT.Storage" throughout the homepage

**Comment by dashcraft** [comment]
@dchoi27 after this latest deploy finishes, can you check that the styles match up to what you envisioned for the about section, I matched the width of the faq content towards the bottom.

**Comment by dchoi27** [comment]
Thanks! I'm sorry to yank you around a bit, but now that I'm looking at it, I think the center justification of the text looks kind of crazy. Can we try two columns both left justified, with the first paragraph in the left column and the second and third paragraphs in the right (can also try combining them into one paragraph)? And make the overall margins smaller (closer to the width of the description at the top of the page, `Free decentralized...`?

If this still doesn't look great, I can loop in designer help.

**Comment by dashcraft** [comment]
> Thanks! I'm sorry to yank you around a bit, but now that I'm looking at it, I think the center justification of the text looks kind of crazy. Can we try two columns both left justified, with the first paragraph in the left column and the second and third paragraphs in the right (can also try combining them into one paragraph)? And make the overall margins smaller (closer to the width of the description at the top of the page, `Free decentralized...`?
> 
> If this still doesn't look great, I can loop in designer help.

No worries! Yank the chain all you want!!

**Comment by dashcraft** [comment]
@dchoi27 im going to say that i don't personally prefer this layout, feels too disconnected from the store portion beneath it. Give it a look and let me know what you think!

**Comment by dashcraft** [comment]
image

**Comment by dchoi27** [comment]
Yeah agreed. Going to loop in designer help!

**Review by dchoi27 — APPROVED** [review]
Looks good! The last paragraph in Store should be updated to what's in the issue, but otherwise good to merge from a content and visual standpoint.

**Pull request merged**
