### PR TITLE
Fix: issue 1307 update logo

### PR DESCRIPTION
**Pull request by cmunns**
We really needed to crisp up the legibility of the logo which I've done as well as made it inline to prevent the max-height in the navbar from squishing it too much. A final note; in light of nftstorage.com being a separate entity, I think its important at least for the time being to have the NFT Storage logo actually include the [dot] to drive home the top level domain used.
Screen Shot 2022-02-08 at 11 26 37 AM
Screen Shot 2022-02-09 at 9 20 39 AM
Screen Shot 2022-02-09 at 9 13 47 AM
Screen Shot 2022-02-09 at 9 13 57 AM

### CODE REVIEW

**Review by Codigo-Fuentes — CHANGES_REQUESTED** [review]
On some smaller mobile screens, the new logo is too scrunched / doesn't fit.  SSs forthcoming.

**Comment by Codigo-Fuentes** [comment]
Screen Shot 2022-02-10 at 8 55 36 PM

**Comment by Codigo-Fuentes** [comment]
> Screen Shot 2022-02-10 at 8 55 36 PM

**Chore:** Can we also fix the vertical alignment of the buttons; they are clearly staggered

**Comment by Codigo-Fuentes** [comment]
**Issue:** On some smaller mobile screens, the new logo is too scrunched / doesn't fit. SSs forthcoming.

**Comment by cmunns** [comment]
Screen Shot 2022-02-10 at 4 18 48 PM

**Review by Codigo-Fuentes — APPROVED** [review]

**Pull request merged**
