### PR TITLE
feat:pare down homepage

### LINKED ISSUE #966: Refine homepage content with improved get started section & removed /docs and /faqs content
Along with #796 being pushed, we should pare down the information on the homepage. The Store and Retrieve sections can probably become smaller since that will be information in the docs. We should also think about the "Getting Started" code snippets at the bottom and whether we want to edit those. cc @yusefnapora 

## Notes
First pass on this would be to move all "docs" related content from homepage into our new Docs page, thus reducing amount o f content on homepage

### PR DESCRIPTION
**Pull request by dashcraft**
Removes faq section and docs at bottom of homepage

fixes #966 

- [x] use the #336BAD blue for links (better contrast on yellow, still part of brand colors)
- [x] change section title capitalization to "Getting started is easy" 
- [x] No comma after 'and' in this text: "Mint your NFTs on any blockchain, and share them with any gallery."
- [x] ensure branch is latest, since in CI preview link I see the older logo on homepage. 
- [x] update capitalization and punctuation in copy above the "View Docs" cta to be:  "Are you a developer? We have an API for that!"

### CODE REVIEW

**Review by cmunns — APPROVED** [review]
looks good.

**Comment by dashcraft** [comment]
This one needs to be coordinated with docs deployment

**Comment by cmunns** [comment]
Rework of getting started area to be more generic callout for signing up and sending devs to docs where technical info has migrated...
Screen Shot 2022-02-22 at 10 18 35 AM
Screen Shot 2022-02-22 at 10 07 17 AM

**Review by dchoi27 — CHANGES_REQUESTED** [review]
Love the direction here! Can we add @yusefnapora as a reviewer as well? We should make sure that the information that was previously on the homepage is represented in the docs in a way that flows from the new homepage.

Some feedback:
- Can we structure the steps like: (1) Create an NFT.Storage account and API key, (2) Upload your files using code or the website, and use the IPFS link in your NFT and metadata
- Can we add something underneath to the effect of: "Uploaded data will be accessible on the IPFS network and perpetually and verifiably stored by multiple Filecoin storage providers!"
- And then "Are you a developer..." (let's not capitalize "You" and "Developer")

**Comment by Codigo-Fuentes** [comment]
**praise**: New layout looks great. Much cleaner.

**Review by Codigo-Fuentes — CHANGES_REQUESTED** [review]
**issue(blocking)**: The yellow (tachyons bg-yellow: #FFD700) and blue (nsblue: #47AEd7) do not have sufficient contrast (contrast ration of 1.8).

The previous blue color (nsnavy: #336BAD) passed AA with contrast ratio of 3.89 which is still not great for me. Can we revert to that color or choose another please?

**Comment by Codigo-Fuentes** [comment]
**nitpick (blocking)**:  The text "Getting started is Easy" should have consistent capitalization; i.e., either "Getting started is easy" or "Getting Started is Easy". 

I believe the former (only the first letter capitalized) is more consistent with site styles but those are not 100% consistent.

**Comment by Codigo-Fuentes** [comment]
**suggestion (non-blocking)**: No comma after 'and' in this text: "Mint your NFTs on any blockchain, and share them with any gallery."

**Comment by JeffLowe** [comment]
@cmunns added all actionable tasks for this pr in the description.  We may have some additional copy adjustments to make once David responds.

**Comment by dchoi27** [comment]
Thanks, makes sense on the API key. I had mostly suggested including it to balance out steps 1 and 2.

On copy, the About section already includes information about data being available on IPFS and stored on Filecoin. The point of including it down here would be to emphasize the point of what the service does (which doesn't always land with folks).

Maybe we take Step 1 as you suggest ("Create an NFT.Storage account and start uploading your files to IPFS. Your data will be accessible on the IPFS network where it is perpetually and verifiably stored by multiple Filecoin storage providers!") and have Step 2 be:
"Use IPFS links when minting your NFT and metadata. As long as your NFT uses IPFS content identifiers (a [hash](https://docs.ipfs.io/concepts/content-addressing/) of the data), no one can dispute what content your NFT is referring to!"

Think length might be an issue though.

**Comment by cmunns** [comment]
Updated that copy.
Screen Shot 2022-02-24 at 8 56 08 AM

**Review by dchoi27 — APPROVED** [review]
LGTM!

**Review by Codigo-Fuentes — APPROVED** [review]

**Pull request merged**
