### PR TITLE
fix (website): safari buttons for mobile menu

### PR DESCRIPTION
**Pull request by the-simian**
fixes the way the mobile menu looks in safari

### CODE REVIEW

**Comment by the-simian** [comment]
Got this looking correct now: 
image

**Comment by the-simian** [comment]
@dashcraft come check this out and review it

**Review by dashcraft — APPROVED** [review]
LGTM!

**Comment by dashcraft** [comment]
It feels like the interface or rendering pattern might be a few more iterations from settling down, but this feels much better and solves the safari issue.

**Pull request merged**
