### PR TITLE
Feat/doc styles

### PR DESCRIPTION
**Pull request by the-simian**
styles the docs to look like the site, an accessible nft.storage swagger 4.x theme

1. This uses the material from (https://github.com/nftstorage/nft.storage/pull/709) , which I pulled into a branch from @msecret 's fork
2. Resolves https://github.com/nftstorage/nft.storage/issues/362
3. This replaces the swagger 4.x theme with an nft.storage theme, which is loaded in the _app.js, like any non-module CSS. (it must be done this way. Since this is our theme, there's no need to use any CSS hacks to override swagger, we just load this one file now
4. There are additional vars added to the `global.css` file in order to hydrate the swagger theme such as additional grayscale values, default border properties
5. This is more responsive than the previous theme, but I did not exhaustively check every known device (see screenshots below)
6. I added the class `nft-storage` at the root of the app. I ended up not using this as an CSS overriding strategy but I think its worth leaving.
7. General cleanup: Some spicier animations, and various sizing/spacing fixes (eg. previous docs screen wouldn't go the whole page when items were collapsed). Too many to list, so I included several before/after screenshots below

### CODE REVIEW

**Comment by the-simian** [comment]
image

**Comment by the-simian** [comment]
image

**Comment by the-simian** [comment]
image

**Comment by the-simian** [comment]
spicier

**Comment by the-simian** [comment]
Before/After (items collapsed)
image

**Comment by the-simian** [comment]
Before/After (modal)
image

**Comment by the-simian** [comment]
Before/After (inside the opblocks)
image

**Comment by the-simian** [comment]
Before/ After (Schemas)
image

(probably the least has changed here other than border/spacing, but mainly checking there's no regressions)

**Review by alanshaw — APPROVED** [review]
Thanks @msecret and @the-simian ❤️

**Pull request merged**
