### PR TITLE
feat: update browser examples

### PR DESCRIPTION
**Pull request by alanshaw**
Updates the examples to use the bundle from the jsdelivr CDN instead of skypack (we are still working through the issues with that bundler).

Added a `storeCar.html` browser example which uses the `NFTStorage.encodeBlob` function.

Also, since the bundle now works, the `car` example has been renamed to be an example of how to bundle using vite.

I also removed the `endpoint` from the examples since it's an option that most users do not need to change.

### CODE REVIEW

**Comment by jimaek** [comment]
jsDelivr also has bundling https://www.jsdelivr.com/esm
Let us know if its missing anything you need

**Review by yusefnapora — APPROVED** [review]
lgtm 👍

**Review by vasco-santos — APPROVED** [review]
Awesome! ❤️

**Comment by alanshaw** [comment]
@jimaek thank you, but it looks like it doesn't support [`package.json` `exports`](https://nodejs.org/api/packages.html#packages_exports) field yet :(

**Pull request merged**
