### PR TITLE
feat: temp mailto link for pinning access

### PR DESCRIPTION
**Pull request by cmunns**
Screen Shot 2022-03-03 at 8 54 44 AM
Screen Shot 2022-03-03 at 8 50 16 AM
Screen Shot 2022-03-03 at 8 50 09 AM

### CODE REVIEW

**Review by Codigo-Fuentes — CHANGES_REQUESTED** [review]
**todo:** Mail icon should be vertically centered in button but is not on desktop chrome, e.g.

off-center

**Comment by Codigo-Fuentes** [comment]
**question:** Do we really want to use mailto? On desktop on my computer, clicking the button does nothing, on iPhone it asks me to reinstall mail app (which I wouldn't do).

mail-to

**Comment by JeffLowe** [comment]
> 

Yes.  This is the requested immediate approach to giving users ability to request pinning service access.  As soon as requests table implemented, we'll move to webform  ( see https://github.com/nftstorage/nft.storage/issues/1410

**Comment by cmunns** [comment]
> 

It's an `a/link` tag. Are you seeing it get stripped out ?

**Comment by cmunns** [comment]
@Codigo-Fuentes switched to icon. After this gets updated to use webform we can use the button component to toggle the modal for that.
Screen Shot 2022-03-08 at 2 16 53 PM

**Review by Codigo-Fuentes — APPROVED** [review]

**Pull request merged**
