### PR TITLE
fix: update global button hover so button drops toward shadow

### PR DESCRIPTION
**Pull request by cmunns**
New global hover also accounts for a bit of offset to keep the button centered despite change in hover direction.
https://user-images.githubusercontent.com/1189523/156623765-d1aafe3b-8589-4089-8e80-d530f28caeab.mov

### CODE REVIEW

**Review by Codigo-Fuentes — CHANGES_REQUESTED** [review]
**issue (blocking):** Appears to introduce bug that causes login button to disappear (see video below)


https://user-images.githubusercontent.com/43380153/157057046-d6480ef6-e077-46b3-8e43-16fabe598b3f.mp4

**Comment by cmunns** [comment]
@Codigo-Fuentes side effect of using FF for development I guess. Easy fix, Chrome only. Really nice catch on this one! Owe you one.

**Comment by Codigo-Fuentes** [comment]
@cmunns still disappearing for me

**Comment by Codigo-Fuentes** [comment]
https://user-images.githubusercontent.com/43380153/157449414-408cb4b5-0bd8-4a45-9533-3ef26d2ce46c.mp4

**Review by Codigo-Fuentes — APPROVED** [review]

**Pull request merged**
